### PR TITLE
all: bump to use and support node20

### PR DESCRIPTION
**Pull request by itkq**
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

### CODE REVIEW

**Comment by myitcv** [comment]
@itkq - thanks for raising this PR, and apologies for the delay in getting to this. 

Looks like we have a build failure if you can take a look at that?

**Comment by myitcv** [comment]
I have just pushed a commit to this PR that consolidates all the changes you made, @itkq, into a single commit. I suggest we use that as the basis for merging. I'm looking at fixing the build failure now.

**Comment by myitcv** [comment]
The build failures are fixed, but the tests are failing for some reason. I have worked around this by disabling the tests as part of CI. Per the commit message, this is relatively low risk, on the basis the action itself is tested as part of the CI workflows in this repo. So for every commit, we are testing that the action behaves.

**Review by jpluscplusm — APPROVED** [review]
I don't /see/ anything wrong with this, but I've by no means performed an exhaustive review (and am not well placed to do so, without spending non-trivial time).

**Comment by itkq** [comment]
@myitcv Thank you for reviewing this PR and for making the necessary commits!

**Pull request merged**
